services:
  - type: web
    name: imagenesis-webapp
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.19
      - key: FLASK_ENV
        value: production
