services:
  - type: web
    name: imagenesis-webapp
    env: docker
    region: frankfurt
    plan: free
    buildCommand: ""
    startCommand: ""
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /
